/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobilefile;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.lang.*;
import java.util.Scanner;
/**
 *
 * @author user
 */
class record
{
public String product_id,product_name,category_name,product_quantity,product_Price,doa,dob,ind,hash;

};
public class add extends javax.swing.JFrame {
 int no;
    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    
        
        Scanner reader;
        String buffer;
        try
        {
            reader=new Scanner(new File("r.txt"));
           reader.useDelimiter(",");
            while(reader.hasNext())
            {
               buffer=reader.next();
                if(buffer.equals("#"))
                    no++;
           }
          System.out.println("No:"+no);
        }
        catch(FileNotFoundException e)
        {
            System.out.println(e);          
        }
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbDate = new javax.swing.JComboBox();
        cbmonth = new javax.swing.JComboBox();
        cbYear = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        product_id = new javax.swing.JTextField();
        cbDate1 = new javax.swing.JComboBox();
        cbmonth1 = new javax.swing.JComboBox();
        cbYear1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("ADD A NEW RECORD");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 330, 36));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Product ID");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 180, 24));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Product Name");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Category Name");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 180, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Product quantity");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 180, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Product Price");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 180, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Date of purchase");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 180, -1));

        cbDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDateActionPerformed(evt);
            }
        });
        getContentPane().add(cbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        cbmonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonthActionPerformed(evt);
            }
        });
        getContentPane().add(cbmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        cbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yyyy", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        cbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearActionPerformed(evt);
            }
        });
        getContentPane().add(cbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        txtPrice.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 177, -1));

        txtQuantity.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 177, -1));

        txtcategory.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 177, -1));

        txtName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 177, -1));

        product_id.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        getContentPane().add(product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 177, -1));

        cbDate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDate1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        cbmonth1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbmonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonth1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbmonth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        cbYear1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yyyy", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(cbYear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Date of Adding");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 180, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 60, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automobilefile/Screenshot (210).png"))); // NOI18N
        jLabel7.setText("ba");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1870, 990));

        Back.setText("Back");
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDateActionPerformed

    private void cbmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonthActionPerformed

    private void cbDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDate1ActionPerformed

    private void cbmonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonth1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       record rec[]=new record[50];
       record temp=new record();
       record temp1=new record();
       record re[]=new record[50];
       record re1[]=new record[50];
         String buffer,
         ordno=product_id.getText().trim(),
         name = txtName.getText(),
         gender = txtcategory.getText(),
         fathername= txtQuantity.getText(),
         place = txtPrice.getText(),
         doi=cbYear.getSelectedItem()+"/"+cbmonth.getSelectedItem()+"/"+cbDate.getSelectedItem(),
         dob=cbYear1.getSelectedItem()+"/"+cbmonth1.getSelectedItem()+"/"+cbDate1.getSelectedItem(); 
         System.out.println("hello1");
        
       String no1=Integer.toString(no);
       
       
       if(no>=1){
       try{
           Scanner reader3=new Scanner(new File("i.txt"));
           reader3.useDelimiter(",");
           for(int i=0;i<no;i++)
           re[i]=new record();
           for(int j=0;j<no;j++)
           {
               
               re[j].product_id=reader3.next().trim();
               re[j].ind=reader3.next().trim();
               System.out.println("product_id "+re[j].product_id+" "+re[j].ind);
               int o=Integer.parseInt(re[j].product_id);
                //System.out.println("dusra "+re[j].ordno.length()+" "+o+" "+s_ordno);
               if(re[j].product_id.equals(ordno)){
                   
                   JOptionPane.showMessageDialog(rootPane,"product ID already exists");
                   setVisible(false);
                   System.exit(0);
                   
                   
                   
               }}}
       catch(Exception e){
           System.out.println(e);
       }
           }          
                   
             
      try{
          FileWriter fw=new FileWriter("r.txt",true);
               fw.write(no1);
               fw.write(",");  
               fw.write(ordno);
               fw.write(",");
               fw.write(name);
               fw.write(",");
               fw.write(gender);
               fw.write(",");
               fw.write(fathername);
               fw.write(",");
               fw.write(place);
               fw.write(",");
               fw.write(doi);
               fw.write(",");
               fw.write(dob);
               fw.write(",");
               fw.write("#");
               fw.write(",");
               fw.write("\r\n");
               fw.close();
               JOptionPane.showMessageDialog(rootPane,"Inserted record");
       }
       catch (HeadlessException | IOException e)
       {
           JOptionPane.showMessageDialog(rootPane,"Error in record");
       }
        try
       {
           try (FileWriter fw1=new FileWriter("i.txt",true)) {
              fw1.write(ordno);
               fw1.write(",");
              fw1.write(no1);
              //fw1.write(",");
            // fw1.write("/");
             fw1.write(",");
              
              fw1.write("\n\r");
              //fw1.write("\n");
               fw1.close();
           }
            JOptionPane.showMessageDialog(rootPane,"Inserted index");
            
            System.out.println(ordno);
            System.out.println(no1);
       }
       catch (HeadlessException | IOException e)
       {
             JOptionPane.showMessageDialog(rootPane,"Error in index");      
       }
       
       
       
       try
       {
           try (FileWriter fw2=new FileWriter("s.txt",true)) {
               fw2.write(name+","+ordno+",\n");
               //fw2.write(",");
               //fw2.write(ordno);
               //fw2.write(",");
               //fw2.write("\r\n");
               fw2.close();
           }
            JOptionPane.showMessageDialog(rootPane,"Inserted secondary index");
       }
       catch (HeadlessException | IOException e)
       {
             JOptionPane.showMessageDialog(rootPane,"Error in sec ind");      
       }
       
       
       
      Scanner reader;
     
        try
        {
            no=0;
            reader=new Scanner(new File("r.txt"));
            reader.useDelimiter(",");
            while(reader.hasNext())
            {
                buffer=reader.next();
                if(buffer.equals("#"))
                    no++;
            }
            System.out.println("No:"+no);
        }
        catch(FileNotFoundException e)
        {
            System.out.println(e);          
        }
        
        
        for(int i=0;i<no;i++)
        {
            rec[i]=new record();
            //re[i]=new record();
            //re1[i]=new record();
        }
        
        
        try
        {
            Scanner reader1;
            reader1=new Scanner(new File("i.txt"));
            reader1.useDelimiter(",");
            int i=0;
            for(i=0;i<no;i++)
            {
                rec[i].product_id=reader1.next().trim();
                rec[i].ind=reader1.next().trim();
                
               
            }
            reader1.close();
            //sorting
            }
        catch(Exception e)
        {
            System.out.println(e.getStackTrace());
        }
            
           for(int i=0;i<no-1;i++)
            {
                for(int k=0;k<no-1-i;k++)
                {int x=Integer.parseInt(rec[k].product_id);
                int y=Integer.parseInt(rec[k+1].product_id);
                    if(x>y)
                    {
                        temp1=rec[k];
                        rec[k]=rec[k+1];
                        rec[k+1]=temp1;
                    }
                }
            }
            
            
           
            try{
                FileWriter fw1 = new FileWriter("i.txt");
                    for(int i=0;i<no;i++)
                        fw1.write(rec[i].product_id+","+rec[i].ind+",\n\r");
                        
            
                    fw1.close();
            }
            catch(Exception e)
            {
                System.out.println(e);  
            }
            
       
        try
        {
           
           try  {
               Scanner reader2 = new Scanner(new File("s.txt"));
               reader2.useDelimiter(",");
               
               for(int i=0;i<no;i++)
               {
                   rec[i].product_name=reader2.next().trim();
                   rec[i].product_id=reader2.next().trim();
                  // System.out.println(rec[i].name+"  "+rec[i].ordno);
               }
           }
           catch(Exception e)
        {
            System.out.println(e);
        }
        
           try{ 
            //String re1,re2;
            for(int i=0;i<no-1;i++)
            {
                for(int k=0;k<no-1-i;k++)
                {
                    if(rec[k].product_name.compareTo(rec[k+1].product_name)>0)
                    {
                        temp=rec[k];
                        rec[k]=rec[k+1];
                        rec[k+1]=temp;
                    }
                }
            }
            
           // System.out.println("sorted order:");
           // for(int i=0;i<no;i++)
           // {
                
           //     System.out.println(rec[i].name+"  "+rec[i].ordno);
               
            //}
           }
           catch(Exception e){
               System.out.print(e.getStackTrace());
           }
            FileWriter fw2;
            try{
                fw2=new FileWriter("s.txt");
                for(int i=0;i<no;i++)
                {
                    fw2.write(rec[i].product_name);
                    fw2.write(",");
                    fw2.write(rec[i].product_id);
                    fw2.write(",");
                    fw2.write("\r\n");
                }
                fw2.close();
            }
            catch(Exception e)
            {
                System.out.println(e);  
            }
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
        
     
      
       
        
                             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox cbDate;
    private javax.swing.JComboBox cbDate1;
    private javax.swing.JComboBox cbYear;
    private javax.swing.JComboBox cbYear1;
    private javax.swing.JComboBox cbmonth;
    private javax.swing.JComboBox cbmonth1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtcategory;
    // End of variables declaration//GEN-END:variables
}
