/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobilefile;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class deletion extends javax.swing.JFrame {
int no;
    /**
     * Creates new form deletion
     */
    public deletion() {
        initComponents();
         no=0;
         Scanner reader;
        String buffer;
        try {
            reader = new Scanner (new File("r.txt"));
            reader.useDelimiter(",");
            while(reader.hasNext())
            {
                buffer=reader.next();
                if(buffer.equals("#"))
                    no++;
            }
            System.out.println("No: "+no);
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtOrdno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Enter product ID to delete:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 280, -1));

        txtOrdno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtOrdno, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 177, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automobilefile/Screenshot (210).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1730, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        record re[]=new record[50];
         record rec[]=new record[50];
          record temp=new record();
       record temp1=new record();
        String buffer;
        int index=999;
        for(int i=0;i<no+2;i++)
        re[i]=new record();
        for(int i=0;i<no+2;i++)
        rec[i]=new record();
        Scanner reader2;
        //String s_name=txtOrdno.getText().trim();
        int s_ordno=Integer.parseInt(txtOrdno.getText());
        //System.out.println(s_name.length());
        int imp=0;
        try{
            reader2=new Scanner(new File("r.txt"));
            reader2.useDelimiter(",");
            for(int i=0;i<no;i++)
            {
                                        re[i].ind=reader2.next().trim();
                                        re[i].product_id=reader2.next().trim();
                                        re[i].product_name=reader2.next().trim();
                                        re[i].category_name=reader2.next().trim();
                                        re[i].product_quantity=reader2.next().trim();
                                        re[i].product_Price=reader2.next().trim();
                                        re[i].dob=reader2.next().trim();
                                        re[i].doa=reader2.next().trim();
                                        re[i].hash=reader2.next().trim();
                //System.out.println(re[i].name+" "+re[i].name.length());
                                        int del=Integer.parseInt(re[i].product_id);
                                         System.out.println("del="+del);
            
            if(del==s_ordno){
                index=Integer.parseInt(re[i].ind);
            
            }}}catch(Exception e){
            System.out.println("exception   "+e);
        }
                
                    if(index==999){
                        System.out.println("record not found");
                          JOptionPane.showMessageDialog(rootPane,"record not found");
                          System.exit(0);
                        
                    }
                       
                    else if(index==no){
                        no--;
                    }
                    
                    else{
                    for(int k=index;k<no;k++){
                    System.out.println("k="+k+"  k+1="+(k+1));
                    System.out.println("k+1 ka index and no= "+re[k+1].ind+" "+re[k+1].product_id);
                        re[k]=re[(k+1)];
                    }
                    no--;
                     }
                
                    
             
        
        
        System.out.println("no:"+no);
         for(int l=0;l<no;l++)System.out.println("rec ka"+re[l].ind);
         try{
          FileWriter fw=new FileWriter("r.txt");
          for(int l=0;l<no;l++){
              
          System.out.println("forloop k andar"+l+" "+no);
              System.out.println(re[l].product_name+" "+re[l].product_id+" "+re[l].category_name+" "+re[l].product_Price+" "+re[l].product_quantity+" "+re[l].dob+" "+re[l].doa+" ");
          fw.write(""+l);
               fw.write(",");  
               fw.write(re[l].product_id);
               fw.write(",");
               fw.write(re[l].product_name);
               fw.write(",");
               fw.write(re[l].category_name);
               fw.write(",");
               fw.write(re[l].product_quantity);
               fw.write(",");
               fw.write(re[l].product_Price);
               fw.write(",");
               fw.write(re[l].dob);
               fw.write(",");
               fw.write(re[l].doa);
               fw.write(",");
               fw.write("#");
               fw.write(",");
               fw.write("\r\n");
          }
               fw.close();
               //JOptionPane.showMessageDialog(rootPane,"Inserted record");
       }
       catch (Exception e)
       {
           System.out.println(e+" "+e.getStackTrace());
       }
         
          try
       {
           try (FileWriter fw1=new FileWriter("i.txt")) {
               for(int i=0;i<no;i++) 
              fw1.write(re[i].product_id+","+i+",\n");
              
               fw1.close();
           }
            JOptionPane.showMessageDialog(rootPane,"Updated index");
            
           
       }
       catch (HeadlessException | IOException e)
       {
             JOptionPane.showMessageDialog(rootPane,"Error in index");      
       }
          
          try
       {
           try (FileWriter fw2=new FileWriter("s.txt")) {
               
               for(int i=0;i<no;i++) 
               fw2.write(re[i].product_name+","+re[i].product_id+",\n");
               
               fw2.close();
           }
            JOptionPane.showMessageDialog(rootPane,"Updated secondary index");
       }
       catch (HeadlessException | IOException e)
       {
             JOptionPane.showMessageDialog(rootPane,"Error in sec ind");      
       }
          
          
          
           Scanner reader;
     
        try
        {
            no=0;
            reader=new Scanner(new File("r.txt"));
            reader.useDelimiter(",");
            while(reader.hasNext())
            {
                buffer=reader.next();
                if(buffer.equals("#"))
                    no++;
            }
            System.out.println("No:"+no);
        }
        catch(FileNotFoundException e)
        {
            System.out.println(e);          
        }
        
        
        for(int i=0;i<no;i++)
        {
            rec[i]=new record();
            //re[i]=new record();
            //re1[i]=new record();
        }
        
        
        try
        {
            Scanner reader1;
            reader1=new Scanner(new File("i.txt"));
            reader1.useDelimiter(",");
            int i=0;
            for(i=0;i<no;i++)
            {
                rec[i].product_id=reader1.next().trim();
                rec[i].ind=reader1.next().trim();
                
               
            }
            reader1.close();
            //sorting
            }
        catch(Exception e)
        {
            System.out.println(e.getStackTrace());
        }
            
           for(int i=0;i<no-1;i++)
            {
                for(int k=0;k<no-1-i;k++)
                {int x=Integer.parseInt(rec[k].product_id);
                int y=Integer.parseInt(rec[k+1].product_id);
                    if(x>y)
                    {
                        temp1=rec[k];
                        rec[k]=rec[k+1];
                        rec[k+1]=temp1;
                    }
                }
            }
            
            
           
            try{
                FileWriter fw1 = new FileWriter("i.txt");
                    for(int i=0;i<no;i++)
                        fw1.write(rec[i].product_id+","+rec[i].ind+",\n");
                    fw1.close();
            }
            catch(Exception e)
            {
                System.out.println(e);  
            }
            
       
        try
        {
           
           try  {
               Scanner reader3 = new Scanner(new File("s.txt"));
               reader3.useDelimiter(",");
               
               for(int i=0;i<no;i++)
               {
                   rec[i].product_name=reader3.next().trim();
                   rec[i].product_id=reader3.next().trim();
                  // System.out.println(rec[i].name+"  "+rec[i].ordno);
               }
           }
           catch(Exception e)
        {
            System.out.println(e);
        }
        
           try{ 
            //String re1,re2;
            for(int i=0;i<no-1;i++)
            {
                for(int k=0;k<no-1-i;k++)
                {
                    if(rec[k].product_name.compareTo(rec[k+1].product_name)>0)
                    {
                        temp=rec[k];
                        rec[k]=rec[k+1];
                        rec[k+1]=temp;
                    }
                }
            }
            
           // System.out.println("sorted order:");
           // for(int i=0;i<no;i++)
           // {
                
           //     System.out.println(rec[i].name+"  "+rec[i].ordno);
               
            //}
           }
           catch(Exception e){
               System.out.print(e.getStackTrace());
           }
            FileWriter fw2;
            try{
                fw2=new FileWriter("s.txt");
                for(int i=0;i<no;i++)
                {
                    fw2.write(rec[i].product_name);
                    fw2.write(",");
                    fw2.write(rec[i].product_id);
                    fw2.write(",");
                    fw2.write("\r\n");
                }
                fw2.close();
            }
            catch(Exception e)
            {
                System.out.println(e);  
            }
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
        
          

        //System.out.println(re[imp].name+" "+re[imp].ordno+" "+re[imp].gender+" "+re[imp].place+" "+re[imp].fathername+" "+re[imp].dob+" "+re[imp].doi+" ");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtOrdno;
    // End of variables declaration//GEN-END:variables
}
