/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobilefile;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class view extends javax.swing.JFrame {
int no;
    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        no=0;
         Scanner reader;
        String buffer;
        try {
            reader = new Scanner (new File("r.txt"));
            reader.useDelimiter(",");
            while(reader.hasNext())
            {
                buffer=reader.next();
                if(buffer.equals("#"))
                    no++;
            }
            System.out.println("No: "+no);
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
         record re[]=new record[100];
         for(int i=0;i<100;i++)
            re[i]=new record();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        String extra;
        try{
       
        File file = new File("r.txt");
            Scanner reader4=new Scanner(file);
            reader4.useDelimiter(",");
            for(int k=0;k<no;k++)
            {
                re[k].ind=reader4.next().trim();
               re[k].product_id=reader4.next().trim();
               re[k].product_name=reader4.next().trim();
               re[k].category_name=reader4.next().trim();
               re[k].product_quantity=reader4.next().trim();
               re[k].product_Price=reader4.next().trim();
               re[k].dob=reader4.next().trim();
               re[k].doa=reader4.next().trim();
               re[k].hash=reader4.next().trim();

            }
        }
        catch(Exception e){}
                
            for(int i=0;i<no;i++)
        {
           
            model.addRow(new Object[]{re[i].product_id,re[i].product_name,re[i].category_name,re[i].product_quantity,re[i].product_Price,re[i].doa,re[i].dob});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_id", "product_name", "category_name", "product_quantity", "product_price", "Date of adding", "Date of birth"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 1040, 180));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel6.setText("VIEW OF RECORDS");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 310, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automobilefile/Screenshot (210).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 1780, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
